from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Concert(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, _date=None, venue=None, city=None, state=None, country=None, extra_info=None, notes=None, acknowledgments=None):  # noqa: E501
        """Concert - a model defined in OpenAPI

        :param id: The id of this Concert.  # noqa: E501
        :type id: int
        :param _date: The _date of this Concert.  # noqa: E501
        :type _date: date
        :param venue: The venue of this Concert.  # noqa: E501
        :type venue: str
        :param city: The city of this Concert.  # noqa: E501
        :type city: str
        :param state: The state of this Concert.  # noqa: E501
        :type state: str
        :param country: The country of this Concert.  # noqa: E501
        :type country: str
        :param extra_info: The extra_info of this Concert.  # noqa: E501
        :type extra_info: str
        :param notes: The notes of this Concert.  # noqa: E501
        :type notes: str
        :param acknowledgments: The acknowledgments of this Concert.  # noqa: E501
        :type acknowledgments: str
        """
        self.openapi_types = {
            'id': int,
            '_date': date,
            'venue': str,
            'city': str,
            'state': str,
            'country': str,
            'extra_info': str,
            'notes': str,
            'acknowledgments': str
        }

        self.attribute_map = {
            'id': 'id',
            '_date': 'date',
            'venue': 'venue',
            'city': 'city',
            'state': 'state',
            'country': 'country',
            'extra_info': 'extra_info',
            'notes': 'notes',
            'acknowledgments': 'acknowledgments'
        }

        self._id = id
        self.__date = _date
        self._venue = venue
        self._city = city
        self._state = state
        self._country = country
        self._extra_info = extra_info
        self._notes = notes
        self._acknowledgments = acknowledgments

    @classmethod
    def from_dict(cls, dikt) -> 'Concert':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Concert of this Concert.  # noqa: E501
        :rtype: Concert
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Concert.


        :return: The id of this Concert.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Concert.


        :param id: The id of this Concert.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def _date(self) -> date:
        """Gets the _date of this Concert.


        :return: The _date of this Concert.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this Concert.


        :param _date: The _date of this Concert.
        :type _date: date
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def venue(self) -> str:
        """Gets the venue of this Concert.


        :return: The venue of this Concert.
        :rtype: str
        """
        return self._venue

    @venue.setter
    def venue(self, venue: str):
        """Sets the venue of this Concert.


        :param venue: The venue of this Concert.
        :type venue: str
        """
        if venue is None:
            raise ValueError("Invalid value for `venue`, must not be `None`")  # noqa: E501

        self._venue = venue

    @property
    def city(self) -> str:
        """Gets the city of this Concert.


        :return: The city of this Concert.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Concert.


        :param city: The city of this Concert.
        :type city: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def state(self) -> str:
        """Gets the state of this Concert.


        :return: The state of this Concert.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Concert.


        :param state: The state of this Concert.
        :type state: str
        """

        self._state = state

    @property
    def country(self) -> str:
        """Gets the country of this Concert.


        :return: The country of this Concert.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Concert.


        :param country: The country of this Concert.
        :type country: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    @property
    def extra_info(self) -> str:
        """Gets the extra_info of this Concert.


        :return: The extra_info of this Concert.
        :rtype: str
        """
        return self._extra_info

    @extra_info.setter
    def extra_info(self, extra_info: str):
        """Sets the extra_info of this Concert.


        :param extra_info: The extra_info of this Concert.
        :type extra_info: str
        """

        self._extra_info = extra_info

    @property
    def notes(self) -> str:
        """Gets the notes of this Concert.


        :return: The notes of this Concert.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes: str):
        """Sets the notes of this Concert.


        :param notes: The notes of this Concert.
        :type notes: str
        """

        self._notes = notes

    @property
    def acknowledgments(self) -> str:
        """Gets the acknowledgments of this Concert.


        :return: The acknowledgments of this Concert.
        :rtype: str
        """
        return self._acknowledgments

    @acknowledgments.setter
    def acknowledgments(self, acknowledgments: str):
        """Sets the acknowledgments of this Concert.


        :param acknowledgments: The acknowledgments of this Concert.
        :type acknowledgments: str
        """

        self._acknowledgments = acknowledgments
