from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NewSong(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, names=None):  # noqa: E501
        """NewSong - a model defined in OpenAPI

        :param names: The names of this NewSong.  # noqa: E501
        :type names: List[str]
        """
        self.openapi_types = {
            'names': List[str]
        }

        self.attribute_map = {
            'names': 'names'
        }

        self._names = names

    @classmethod
    def from_dict(cls, dikt) -> 'NewSong':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewSong of this NewSong.  # noqa: E501
        :rtype: NewSong
        """
        return util.deserialize_model(dikt, cls)

    @property
    def names(self) -> List[str]:
        """Gets the names of this NewSong.


        :return: The names of this NewSong.
        :rtype: List[str]
        """
        return self._names

    @names.setter
    def names(self, names: List[str]):
        """Sets the names of this NewSong.


        :param names: The names of this NewSong.
        :type names: List[str]
        """
        if names is None:
            raise ValueError("Invalid value for `names`, must not be `None`")  # noqa: E501

        self._names = names
